#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.local/bin:~/bin
export PATH

# Temporary time zone
# export TZ=/usr/share/zoneinfo/Australia/Darwin

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xresources &

# Set numlock
numlockx &

# Start tmux
tmux start

# Start polkit agent
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Set ssh-agent key progam
. ~/.local/bin/start-agents
export SSH_ASKPASS=/usr/lib/ssh/x11-ssh-askpass

# Start the system tray
#trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 6 --transparent true --alpha 0 --tint 0x000000 --height 16 &

# Start WM
#exec i3

# Start apps
#urxvt -t term -e bash -c "tmux new-session -A -n$USER -s$USER@$HOSTNAME" &
#urxvt -t code -e bash -c "tmux new-session -A -n$USER -scode" &
#chromium &
#workrave &

# Start screensaver
#xscreensaver -no-splash &

# Start sound server
pulseaudio --start &

# Start redshift
# redshift -l -32.3:115.7 -t 6000:3700 &
redshift-gtk &

# Start WM
exec i3
#exec xmonad
